name: Prueba Devops

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Simular despliegue
      run: 
        echo "Hola mundo"
        echo "Se instalan dependencias node.js"
        echo "Simulamos despliegue, pepiline activo con un push en main"
    
